name: php-composer-build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build php-cli image
        uses: docker/build-push-action@v5
        with:
          context: "."
          target: "php_cli"
          push: true
          tags: |
            devoptimus/php-cli:0.0.1
            devoptimus/php-cli:latest

      - name: Build php-cli image
        uses: docker/build-push-action@v5
        with:
          context: "."
          target: "php_composer"
          push: true
          tags: |
            devoptimus/php-composer:0.0.1
            devoptimus/php-composer:latest

      - name: Docker Hub Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
